[package]
name = "code_01"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.28.1"
egui = "0.28.1"
egui_extras = "0.28.1"
env_logger = "0.11.5"
fltk = "1.4.33"
glib = "0.20.0"
gtk4 = "0.9.0"
lazy_static = "1.5.0"
