[package]
name = "business_app"
version = "0.1.0"
edition = "2021"

[dependencies]
async-std = "1.12.0"
fltk = "1.4.33"
lazy_static = "1.5.0"
tokio = { version = "1.39.2", features = ["full"] }
tokio-postgres = { version = "0.7.11", features = ["with-chrono-0_4"] }
